# where to start with, here we are starting with node with some type since we want to run js file
FROM node:alpine
# here we are copying all files into docker for creating its image
COPY . /app
# here we are switch to the folder which we created 
WORKDIR /app
# here we are running command line code to run the file
CMD node app.js